.. _changes_0_1:

Version 0.1 (2022-04-25)
------------------------

- Initial release (initial commit: 2022-04-20)

- Accelerated coordinate descent solver with a working set strategy

- Accelerated block coordinate descent solver with working sets for multi-task problems

- :math:`\ell_1`, :math:`\ell_1+\ell_2`, MCP, SCAD and box penalties supported

- ``Quadratic``, ``Logistic``, ``LogisticSVM`` datafits supported

- Introduced ``GeneralizedLinearEstimator``
